================================================================================
Appcelerator Titanium Diagnostics Build Log
The contents of this file are useful to send to Appcelerator Support if
reporting an issue to help us understand your environment, build settings
and aid in debugging. Please attach this log to any issue that you report.
================================================================================

Starting build at 10/16/11 06:06

Build details:

   timestamp=07/21/11 09:36
   version=1.7.2
   githash=97c3689


Script arguments:
   /Users/luis/Library/Application Support/Titanium/mobilesdk/osx/1.7.2/iphone/builder.py
   simulator
   4.3
   /Users/luis/Titanium Studio Workspace/Drupanium
   drupaniumapp
   Drupanium
   universal
   iphone
   

Building from: /Users/luis/Library/Application Support/Titanium/mobilesdk/osx/1.7.2/iphone
Platform: Darwin Kernel Version 11.1.0: Tue Jul 26 16:07:11 PDT 2011; root:xnu-1699.22.81~1/RELEASE_X86_64

Xcode path is: /Developer


githash=97c3689, existing_git_hash=97c3689
writing contents of /Users/luis/Titanium Studio Workspace/Drupanium/build/iphone/project.xcconfig:

TI_VERSION=1.7.2
TI_SDK_DIR=/Users/luis/Library/Application Support/Titanium/mobilesdk/osx/$(TI_VERSION)/iphone
TI_APPID=drupaniumapp
OTHER_LDFLAGS[sdk=iphoneos*]=$(inherited) -weak_framework iAd
OTHER_LDFLAGS[sdk=iphonesimulator*]=$(inherited) -weak_framework iAd
#include "module"

old contents



Exception detected in script:
Traceback (most recent call last):
  File "/Users/luis/Library/Application Support/Titanium/mobilesdk/osx/1.7.2/iphone/builder.py", line 899, in main
    force_xcode = write_debugger_plist(debug_plist)
  File "/Users/luis/Library/Application Support/Titanium/mobilesdk/osx/1.7.2/iphone/builder.py", line 714, in write_debugger_plist
    shutil.move(tempfile, debuggerplist)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/pFinishing build
py", line 292, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 127, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 81, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/Users/luis/Titanium Studio Workspace/Drupanium/build/iphone/Resources/debugger.plist.tmp'
